spring.application.name=herniklub

# ?????? ??????????? (?????? ?? ???????? Database ??????)
spring.datasource.url=jdbc:oracle:thin:@fei-sql3.upceucebny.cz:1521:BDAS
spring.datasource.username=ST79048
spring.datasource.password=abcde

# ??????? ??? Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ????? Spring ?? ??????? ?????? ?????? ? ??????????????? ????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=ST79048